-- Realtime CDC and audit log setup for patient_notes is applied
-- after the table is created by the seed script (patient_notes.sql).
-- This migration is intentionally a no-op; the seed handles it.
